### ISSUE TITLE
methods.select function broken - selecting Index 0

### ISSUE THREAD

**Issue by Velron** [prashantchaudhary/ddslick#2]
The public function methods.select is broken when the index is zero. This can be fixed by replacing the if check with the following: 

if ((options.index !== false || options.index !== null) && options.index >= 0)

**Comment by prashantchaudhary** [comment]
Yup, that's a bug!

**Comment by prashantchaudhary** [comment]
This is fixed using Pull Request #16. Closing it now.

**Comment by paritosh-iopex** [comment]
This bug is still experienced. After selecting by index say 4, again selecting index 0 not working.

**Comment by andrewlow** [comment]
There is a work-around http://designwithpc.com/plugins/ddslick#comment-2049064500

Don't pass an integer, pass it as a string

`$('#mydiv').ddslick('select', {index: String(myIndex)});`

**Comment by vostrik** [comment]
You thought about this 8 months?!
